name: Monitor-Daemon
web:
  enabled: false
  port: 1314
  token: some-secure-string-here
system:
  enabled: false
  swapwarn: 200000
  swapReboot: 200000
ddns:
  enabled: false
  ip: 127.0.0.1
  urls: 
    - http://website.com/ddns.php?domain=test.com
    - http://website.com/ddns.php?domain=test2.com
storage:
  enabled: false
  mdadm:
    - /dev/md0
  smart:
    - /dev/sda
  atto:
    - c1
rss: 
  enabled: false
  urls:
    - https://www.feedforall.com/sample.xml
    - https://www.feedforall.com/sample.xml
transmission:
  enabled: false
  path: /opt/transmission
  proxy:
    protocol: socks5
    username: test
    password: test
    hostname: somedomain.com
    port: 1080
telegram:
  enabled: false
  apikey: api-key-id-here
  chatid: 0
plex:
  enabled: false
  plexToken: i-dont-have-plex-pass
  release: "#[label="Ubuntu (16.04+) / Debian (8+) - Intel/AMD 64-bit"]"
  checksum: outofdate